backend:
  name: git-gateway
  branch: main
  squash_merges: true

local_backend: true

publish_mode: editorial_workflow

media_folder: 'assets/uploads' # Where media files will be stored in the repo
