# See documentation at
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "yarn build"
  publish = "public"

[[headers]]
  for = "*.png, *.jpg, *.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff, *.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
    # Optional (but highly recommended). Defaults to [".cache"].
    paths = [".cache", "public"]
