name: 'free_draft' # Used in routes, e.g., /admin/collections/blog
label: 'Free Draft Outdated' # Used in the UI
folder: '_free_draft' # The path to the folder where the documents are stored
create: true # Allow users to create new documents in this collection
slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
fields:
  - { label: 'Title', name: 'title', widget: 'string', required: false }
  - { label: 'Meta description', name: 'description', widget: 'string', required: false }
  - { label: 'Permalink', name: 'permalink', widget: 'string', required: false }
  - { label: 'Favicon', name: 'favicon', widget: 'image', required: false }
  - { label: 'Noindex', name: 'noindex', widget: 'boolean', default: true }
  - { label: 'Show intercom', name: 'intercom', widget: 'boolean', default: false, required: false }
  - label: Hero
    name: hero
    widget: object
    required: false
    fields:
      - { label: 'Logo', name: 'logo', widget: 'image', media_folder: 'images', required: false }
      - { label: 'Logo Alt Text', name: 'logo_alt_text', widget: 'string', required: false }
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Cta', name: 'cta', widget: 'string', required: false }
      - { label: 'Cta Link', name: 'cta_link', widget: 'string', required: false }
  - label: Hero With Hubspot Form
    name: hero_with_hubspot_form
    widget: object
    required: false
    fields:
      - { label: 'Logo', name: 'logo', widget: 'image', media_folder: 'images', required: false }
      - { label: 'Logo Alt Text', name: 'logo_alt_text', widget: 'string', required: false }
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Cta', name: 'cta', widget: 'string', required: false }
  - label: How It Works
    name: how_it_works
    widget: object
    required: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - label: How It Works List
        name: how_it_works_list
        widget: list
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: false }
          - { label: 'Description', name: 'description', widget: 'markdown', required: false }
          - { label: 'Note', name: 'note', widget: 'string', required: false }
  - label: Contact CTA
    name: contact_cta
    widget: object
    required: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - { label: 'Description', name: 'description', widget: 'markdown', required: false }
      - { label: 'Cta', name: 'cta', widget: 'string', required: false }
      - { label: 'Cta Link', name: 'cta_url', widget: 'string', required: false }
