name: 'testimonials'
label: 'Testimonials'
folder: 'src/data/testimonials'
create: true
slug: '{{slug}}'
fields:
  - { label: 'Active', name: 'active', widget: 'boolean', required: true }
  - { label: 'Company name', name: 'company', widget: 'string' }
  - label: Customer
    name: customer
    widget: object
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string', required: false }
      - { label: 'Avatar', name: 'avatar', widget: 'image', required: false }
  - { label: 'Quote', name: 'quote', widget: 'string' }
  - { label: 'Alternative quote', name: 'ai_quote', widget: 'string', required: false }
  - { label: 'Image', name: 'image', widget: 'image', required: false }
  - { label: 'Link', name: 'link', widget: 'string', required: false }
